### PR TITLE
MNT: re-grab the original limits each time

### PR DESCRIPTION
**Pull request by tacaswell**
To prevent multiple identical views from being pushed to the stack.

### CODE REVIEW

**Comment by anntzer** [comment]
Not a fan of the switch in PEP8 recommendation wrt. linebreaks?

**Comment by tacaswell** [comment]
https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes the pep8 linter and the pep8 document https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator disagree and W503 is in our blacklist.

Feel free to squash this locally / discard that change / copy-paste out the useful part.

**Comment by anntzer** [comment]
Ah.  Sorry, I completely missed the other part of the patch (only looking at the removed lines part of the diff) and was wondering why you sent this PR :-)  Yes, looks good, thanks.

**Comment by tacaswell** [comment]
I'm not _that_ passive aggressive.

**Comment by anntzer** [comment]
:-)
Force-pushed to the original PR.

**Pull request closed without merging**
